### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/output/LabelsFilled.nii.gz'

### ISSUE THREAD

**Issue by ccbvib** [csudre/NMJ_Analyser#2]
I have a problem where I have correctly labeled red and green images (i.e. "Mouse1_GREEN_0000.jpg") , but NMJ_Analyzer is not recognizing these images and displaying the following error:

```
nmj_analyzer
X Resolution: "0.48"
Z Resolution: "1.750"
ID: ""
threshold: "64"
Path to images: "~/Documents/nmj_analyzer/NMJ_test/"
Path to saved output: "~/Documents/nmj_analyzer/output/"
0 0
creating threshsize cc
create connective support
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/u0112671/miniconda/envs/nmj_analyzer/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/Users/u0112671/miniconda/envs/nmj_analyzer/lib/python3.7/site-packages/nmj_analyzer/nmj_analyzer.py", line 99, in <lambda>
    command=(lambda e=ents: fetch_and_process(e)))
  File "/Users/u0112671/miniconda/envs/nmj_analyzer/lib/python3.7/site-packages/nmj_analyzer/nmj_analyzer.py", line 14, in fetch_and_process
    process_subject(dict_arg['path_images'], dict_arg['path_save'] , dict_arg['name'], thresh=thresh, pixdim=pixdim)
  File "/Users/u0112671/miniconda/envs/nmj_analyzer/lib/python3.7/site-packages/nmj_analyzer/Processing.py", line 194, in process_subject
    'LabelsFilled'+subject_name+'.nii.gz'))
  File "/Users/u0112671/miniconda/envs/nmj_analyzer/lib/python3.7/site-packages/nibabel/loadsave.py", line 153, in save
    img.to_filename(filename, **kwargs)
  File "/Users/u0112671/miniconda/envs/nmj_analyzer/lib/python3.7/site-packages/nibabel/filebasedimages.py", line 319, in to_filename
    self.to_file_map(**kwargs)
  File "/Users/u0112671/miniconda/envs/nmj_analyzer/lib/python3.7/site-packages/nibabel/nifti1.py", line 2197, in to_file_map
    super().to_file_map(file_map, dtype)
  File "/Users/u0112671/miniconda/envs/nmj_analyzer/lib/python3.7/site-packages/nibabel/analyze.py", line 1046, in to_file_map
    hdrf = hdr_fh.get_prepare_fileobj(mode='wb')
  File "/Users/u0112671/miniconda/envs/nmj_analyzer/lib/python3.7/site-packages/nibabel/fileholders.py", line 70, in get_prepare_fileobj
    obj = ImageOpener(self.filename, *args, **kwargs)
  File "/Users/u0112671/miniconda/envs/nmj_analyzer/lib/python3.7/site-packages/nibabel/openers.py", line 150, in __init__
    self.fobj = opener(fileish, *args, **kwargs)
  File "/Users/u0112671/miniconda/envs/nmj_analyzer/lib/python3.7/site-packages/nibabel/openers.py", line 72, in _gzip_open
    gzip_file = DeterministicGzipFile(filename, mode, compresslevel, mtime=mtime)
  File "/Users/u0112671/miniconda/envs/nmj_analyzer/lib/python3.7/site-packages/nibabel/openers.py", line 57, in __init__
    fileobj = self.myfileobj = open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '~/Documents/nmj_analyzer/output/LabelsFilled.nii.gz'

```

**Comment by alanmejiamaza** [comment]
Hi, still have that problem?
